using PluralsightAndBooksManager.Core;
using System.Collections.Generic;

namespace PluralsightAndBooksManager.WebUI.Helpers
{
    public static class InitialSeedDatabase
    {
        public static List<CourseMaterial> Execute()
        {
            var courseMaterials = new List<CourseMaterial>();
            courseMaterials.Add(new CourseMaterial { Title = "A Better CSS LESS and SASS" });
            courseMaterials.Add(new CourseMaterial { Title = "A Functional Architecture with F#" });
            courseMaterials.Add(new CourseMaterial { Title = "A Tour of PostgreSQL" });
            courseMaterials.Add(new CourseMaterial { Title = "A Web Developer's Guide to Images" });
            courseMaterials.Add(new CourseMaterial { Title = "Accelerated C# Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "ADO.NET Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "Advanced SQL Queries in Oracle and SQL Server" });
            courseMaterials.Add(new CourseMaterial { Title = "Advanced Techniques in JavaScript and jQuery" });
            courseMaterials.Add(new CourseMaterial { Title = "Advanced Unit Testing" });
            courseMaterials.Add(new CourseMaterial { Title = "Algorithms and Data Structures - Part 1" });
            courseMaterials.Add(new CourseMaterial { Title = "Algorithms and Data Structures - Part 2" });
            courseMaterials.Add(new CourseMaterial { Title = "Angular Best Practices" });
            courseMaterials.Add(new CourseMaterial { Title = "AngularJS for .NET Developers" });
            courseMaterials.Add(new CourseMaterial { Title = "AngularJS Forms Using Bootstrap and MVC 5" });
            courseMaterials.Add(new CourseMaterial { Title = "AngularJS Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "AngularJS Get Started" });
            courseMaterials.Add(new CourseMaterial { Title = "AngularJS Line of Business Applications" });
            courseMaterials.Add(new CourseMaterial { Title = "AngularJS Patterns Clean Code" });
            courseMaterials.Add(new CourseMaterial { Title = "Application Building Patterns with AngularJS" });
            courseMaterials.Add(new CourseMaterial { Title = "Architecting Applications for the Real World in .NET" });
            courseMaterials.Add(new CourseMaterial { Title = "Architecting Device-Driven Web Solutions" });
            courseMaterials.Add(new CourseMaterial { Title = "ASP.NET Bundling, Minification & Resource Optimization" });
            courseMaterials.Add(new CourseMaterial { Title = "ASP.NET MVC 3.0 Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "ASP.NET MVC 4 Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "ASP.NET MVC 5 Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "ASP.NET MVC Advanced Topics" });
            courseMaterials.Add(new CourseMaterial { Title = "ASP.NET MVC Testing From Scratch" });
            courseMaterials.Add(new CourseMaterial { Title = "ASP.NET Security Secrets Revealed" });
            courseMaterials.Add(new CourseMaterial { Title = "Asynchronous C# 5.0" });
            courseMaterials.Add(new CourseMaterial { Title = "Automated Testing End to End" });
            courseMaterials.Add(new CourseMaterial { Title = "Automated Testing for Fraidy Cats Like Me" });
            courseMaterials.Add(new CourseMaterial { Title = "Bootstrap 3" });
            courseMaterials.Add(new CourseMaterial { Title = "Build Process, Workflows and Tooling With Grunt.js and Beyond" });
            courseMaterials.Add(new CourseMaterial { Title = "Build Your Own Application Framework with ASP.NET MVC 5" });
            courseMaterials.Add(new CourseMaterial { Title = "Building a Game of Memory with SignalR" });
            courseMaterials.Add(new CourseMaterial { Title = "Building a Site with Bootstrap, AngularJS, ASP.NET, EF and Azure" });
            courseMaterials.Add(new CourseMaterial { Title = "Building Applications with ASP.NET MVC 4" });
            courseMaterials.Add(new CourseMaterial { Title = "Building Apps with Angular and Breeze - Part 1" });
            courseMaterials.Add(new CourseMaterial { Title = "Building Apps with Angular and Breeze - Part 2" });
            courseMaterials.Add(new CourseMaterial { Title = "Building Apps With Durandal 2, MVC 5, Breeze, and Bootstrap 3" });
            courseMaterials.Add(new CourseMaterial { Title = "Building ASP.NET MVC Apps with EF Code First, HTML5, and jQuery" });
            courseMaterials.Add(new CourseMaterial { Title = "Building ASP.Net Web API OData Services" });
            courseMaterials.Add(new CourseMaterial { Title = "Building Data-Centric Single Page Apps with Breeze" });
            courseMaterials.Add(new CourseMaterial { Title = "Building End-to-End Multi-Client Service Oriented Applications - Angular Edition" });
            courseMaterials.Add(new CourseMaterial { Title = "Building HTML5 and JavaScript Apps with MVVM and Knockout" });
            courseMaterials.Add(new CourseMaterial { Title = "Building Web Apps & Services with Entity Framework and Web API" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Collections Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Design Strategies" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Equality and Comparisons" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Events and Delegates" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Extension Methods" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Fundamentals with C# 5.0" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Generics" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Interfaces" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Language Internals - Part 1" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Language Internals - Part 2" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Programming Paradigms" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Tips and Traps" });
            courseMaterials.Add(new CourseMaterial { Title = "C# Tips and Traps 2" });
            courseMaterials.Add(new CourseMaterial { Title = "Caching in the .NET Stack  Inside-Out" });
            courseMaterials.Add(new CourseMaterial { Title = "Clean Code  Writing Code for Humans" });
            courseMaterials.Add(new CourseMaterial { Title = "CLR Threading" });
            courseMaterials.Add(new CourseMaterial { Title = "Creating N-Tier Applications in C#, Part 1" });
            courseMaterials.Add(new CourseMaterial { Title = "Creating N-Tier Applications in C#, Part 2" });
            courseMaterials.Add(new CourseMaterial { Title = "Cross Platform iOSAndroid with Visual Studio and C# - Part 1" });
            courseMaterials.Add(new CourseMaterial { Title = "Cross Platform iOSAndroid with Visual Studio and C# - Part 2" });
            courseMaterials.Add(new CourseMaterial { Title = "Cryptography Fundamentals for Java and .NET Developers" });
            courseMaterials.Add(new CourseMaterial { Title = "CSS3" });
            courseMaterials.Add(new CourseMaterial { Title = "CSS3 From Scratch" });
            courseMaterials.Add(new CourseMaterial { Title = "CSS3 In-Depth" });
            courseMaterials.Add(new CourseMaterial { Title = "Data Layer Validation with Entity Framework 4.1+" });
            courseMaterials.Add(new CourseMaterial { Title = "Debugging the Web" });
            courseMaterials.Add(new CourseMaterial { Title = "Build Process, Workflows and Tooling With Grunt.js and Beyond" });
            courseMaterials.Add(new CourseMaterial { Title = "Defensive Coding in C#" });
            courseMaterials.Add(new CourseMaterial { Title = "Dependency Injection On-Ramp" });
            courseMaterials.Add(new CourseMaterial { Title = "Design Patterns Library" });
            courseMaterials.Add(new CourseMaterial { Title = "Design Patterns On-Ramp" });
            courseMaterials.Add(new CourseMaterial { Title = "Developing a Real World Application With Kendo UI" });
            courseMaterials.Add(new CourseMaterial { Title = "Developing OData Clients" });
            courseMaterials.Add(new CourseMaterial { Title = "Domain-Driven Design Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "Durandal.js Get Started" });
            courseMaterials.Add(new CourseMaterial { Title = "Encapsulation and SOLID" });
            courseMaterials.Add(new CourseMaterial { Title = "Enterprise WPF with XAML and C# from Scratch" });
            courseMaterials.Add(new CourseMaterial { Title = "Entity Framework 4.0 By Example" });
            courseMaterials.Add(new CourseMaterial { Title = "Entity Framework 4.1" });
            courseMaterials.Add(new CourseMaterial { Title = "Entity Framework 4.1 - DbContext Data Access" });
            courseMaterials.Add(new CourseMaterial { Title = "Entity Framework 6 - Ninja Edition - What's New in EF6" });
            courseMaterials.Add(new CourseMaterial { Title = "Entity Framework and Data Models" });
            courseMaterials.Add(new CourseMaterial { Title = "Entity Framework Code First Migrations " });
            courseMaterials.Add(new CourseMaterial { Title = "Entity Framework in the Enterprise" });
            courseMaterials.Add(new CourseMaterial { Title = "Essential Knockout and JavaScript Tips" });
            courseMaterials.Add(new CourseMaterial { Title = "Fixing Common JavaScript Bugs" });
            courseMaterials.Add(new CourseMaterial { Title = "Front-End Web Development Quick Start With HTML5, JavaScript, and CSS" });
            courseMaterials.Add(new CourseMaterial { Title = "Getting Started with ASP.NET MVC, ServiceStack and Bootstrap" });
            courseMaterials.Add(new CourseMaterial { Title = "Getting Started with Entity Framework 5" });
            courseMaterials.Add(new CourseMaterial { Title = "Getting Started with Entity Framework 6" });
            courseMaterials.Add(new CourseMaterial { Title = "Hack-proofing Your ASP.NET Web Applications" });
            courseMaterials.Add(new CourseMaterial { Title = "Hosting SQL Server in Windows Azure IaaS Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "HTML5 Line of Business Apps with Bootstrap, MVC4 and Web API" });
            courseMaterials.Add(new CourseMaterial { Title = "HTML5 Web Storage, IndexedDB and File System" });
            courseMaterials.Add(new CourseMaterial { Title = "HTTP Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "IDisposable Best Practices for C# Developers" });
            courseMaterials.Add(new CourseMaterial { Title = "Implementing an API in ASP.NET Web API" });
            courseMaterials.Add(new CourseMaterial { Title = "Implementing Undo in ASP.NET WebForms and MVC" });
            courseMaterials.Add(new CourseMaterial { Title = "Implementing an API in ASP.NET Web API" });
            courseMaterials.Add(new CourseMaterial { Title = "InDepth Knockout Validation" });
            courseMaterials.Add(new CourseMaterial { Title = "IntelliTrace" });
            courseMaterials.Add(new CourseMaterial { Title = "Introducing ASP.NET SignalR - Push Services with Hubs" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to ASP.NET MVC 3" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to ASP.NET Web Services" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to Async and Parallel Programming in .NET 4" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to Bootstrap" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to Cryptography in .NET" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to Dates and Times in SQL Server" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to Grunt" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to HTML5 and CSS3" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to Kendo UI" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to Localization and Globalization in .NET" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to MongoDB" });
            courseMaterials.Add(new CourseMaterial { Title = "Introduction to the ASP.NET Web API" });
            courseMaterials.Add(new CourseMaterial { Title = "Inversion of control" });
            courseMaterials.Add(new CourseMaterial { Title = "JavaScript Design Patterns" });
            courseMaterials.Add(new CourseMaterial { Title = "JavaScript for C# Developers" });
            courseMaterials.Add(new CourseMaterial { Title = "JavaScript From Scratch" });
            courseMaterials.Add(new CourseMaterial { Title = "JavaScript Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "JavaScript Fundamentals for ES6" });
            courseMaterials.Add(new CourseMaterial { Title = "JavaScript the Good Parts" });
            courseMaterials.Add(new CourseMaterial { Title = "jQuery Advanced Topics" });
            courseMaterials.Add(new CourseMaterial { Title = "jQuery Forms and Bootstrap 3" });
            courseMaterials.Add(new CourseMaterial { Title = "jQuery Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "jQuery Tips and Tricks" });
            courseMaterials.Add(new CourseMaterial { Title = "jQuery-free JavaScript" });
            courseMaterials.Add(new CourseMaterial { Title = "Kendo and MVC From Scratch" });
            courseMaterials.Add(new CourseMaterial { Title = "Kendo UI and AngularJS from Scratch" });
            courseMaterials.Add(new CourseMaterial { Title = "Knockout For the XAML Developer" });
            courseMaterials.Add(new CourseMaterial { Title = "Lessons from Real World .NET Code Reviews" });
            courseMaterials.Add(new CourseMaterial { Title = "LINQ Architecture" });
            courseMaterials.Add(new CourseMaterial { Title = "Mastering C# 4.0" });
            courseMaterials.Add(new CourseMaterial { Title = "Microsoft Fakes Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "Mobile First Responsive Web Design" });
            courseMaterials.Add(new CourseMaterial { Title = "Object-Oriented Programming Fundamentals in C#" });
            courseMaterials.Add(new CourseMaterial { Title = "Outside-In Test-Driven Development" });
            courseMaterials.Add(new CourseMaterial { Title = "OWASP Top 10 Web Application Security Risks for ASP.NET" });
            courseMaterials.Add(new CourseMaterial { Title = "Parent-Child Data With EF, MVC, Knockout, Ajax, and Validation" });
            courseMaterials.Add(new CourseMaterial { Title = "Postgres for .NET Developers" });
            courseMaterials.Add(new CourseMaterial { Title = "Practical Data Modeling With C# and SQL Server" });
            courseMaterials.Add(new CourseMaterial { Title = "Practical IoC With ASP.NET MVC 4" });
            courseMaterials.Add(new CourseMaterial { Title = "Practical LINQ" });
            courseMaterials.Add(new CourseMaterial { Title = "Practical Reflection in .NET" });
            courseMaterials.Add(new CourseMaterial { Title = "Pragmatic Behavior-driven Design with .NET" });
            courseMaterials.Add(new CourseMaterial { Title = "Principles of Object Oriented Design" });
            courseMaterials.Add(new CourseMaterial { Title = "Querying the Entity Framework" });
            courseMaterials.Add(new CourseMaterial { Title = "Real-time Web Applications" });
            courseMaterials.Add(new CourseMaterial { Title = "Real-World ASP.NET MVC3" });
            courseMaterials.Add(new CourseMaterial { Title = "Refactoring Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "REST Fundamentals" });
            courseMaterials.Add(new CourseMaterial { Title = "Search Engine Optimization with ASP.NET" });
            courseMaterials.Add(new CourseMaterial { Title = "SignalR Across Web and Devices" });
            courseMaterials.Add(new CourseMaterial { Title = "Simplifying CSS in Visual Studio With Sass" });
            courseMaterials.Add(new CourseMaterial { Title = "Single Page Apps JumpStart" });
            courseMaterials.Add(new CourseMaterial { Title = "Single Page Apps with HTML5, Web API, Knockout and jQuery" });
            courseMaterials.Add(new CourseMaterial { Title = "SQL Server  Why Physical Database Design Matters" });
            courseMaterials.Add(new CourseMaterial { Title = "SQL Server - Transact-SQL Basic Data Retrieval" });
            courseMaterials.Add(new CourseMaterial { Title = "SQL Server 2012  Transact-SQL Error Handling" });






            return courseMaterials;
        }
    }
}